In [12]:
import requests
from requests import get
import bs4
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

from time import sleep
from random import randint

In [13]:
titles = []
years = []
times = []
imdb_ratings = []
metascores = []
votes = []
us_gross = []

In [14]:
headers = {"Accept-Language": "en-US, en;q=0.5"}

In [15]:
pages = np.arange(1,1001,50)
    
for page in pages: 
  
  page = requests.get("https://www.imdb.com/search/title/?groups=top_1000&start="+str(page)+"&ref_=adv_nxt", headers=headers)
  
  soup = BeautifulSoup(page.text, 'html.parser')
  
  movie_div = soup.find_all('div', class_='lister-item mode-advanced')
  
  sleep(randint(2,10))

## Scraping code

In [7]:
for i in movie_div:
    
    title = i.h3.a.text
    titles.append(title)
    
    year = i.find('span', class_='lister-item-year').text
    years.append(year)
    
    time = i.find('span', class_='runtime').text
    times.append(time)
    
    rating = float(i.strong.text)
    imdb_ratings.append(rating)
    
    score = i.find('span', class_='metascore').text if i.find('span', class_='metascore') else '-'
    metascores.append(score)
    
    nv = i.find_all('span', attrs= {'name':'nv'})
    
    vote = nv[0].text
    votes.append(vote)
    
    gross = nv[1].text if len(nv) > 1 else '-'
    us_gross.append(gross)

In [6]:
print(len(titles))
print(len(years))
print(len(times))
print(len(imdb_ratings))
print(len(metascores))
print(len(votes))
print(len(us_gross))

50
50
50
50
50
50
50

In [62]:
imdb_movies = pd.DataFrame({
    'movie' : titles,
    'year' : years,
    'timeMin' : times,
    'imdb' : imdb_ratings,
    'metascore' : metascores,
    'votes' : votes,
    'us_grossMillions' : us_gross
})

In [63]:
imdb_movies['year'] = imdb_movies['year'].str.extract('(\d+)').astype(int)

imdb_movies['timeMin'] = imdb_movies['timeMin'].str.extract('(\d+)').astype(int)

imdb_movies['votes'] = imdb_movies['votes'].str.replace(',', '').astype(int)

imdb_movies['metascore'] = imdb_movies['metascore'].str.extract('(\d+)')
imdb_movies['metascore'] = pd.to_numeric(imdb_movies['metascore'], errors='coerce')

imdb_movies['us_grossMillions'] = imdb_movies['us_grossMillions'].map(lambda x: x.lstrip('$').rstrip('M'))
imdb_movies['us_grossMillions'] = pd.to_numeric(imdb_movies['us_grossMillions'], errors='coerce')

In [64]:
imdb_movies

,movie,year,timeMin,imdb,metascore,votes,us_grossMillions
0,The Killer,1989,111,7.8,82.0,47338,NaN
1,"Rome, Open City",1945,103,8.1,NaN,25359,NaN
2,Dilwale Dulhania Le Jayenge,1995,181,8.1,NaN,66897,NaN
3,In America,2002,105,7.7,76.0,42575,15.54
4,Lifeboat,1944,97,7.6,78.0,27971,NaN
5,The Lost Weekend,1945,101,7.9,NaN,35663,9.46
6,The Rules of the Game,1939,110,8.0,NaN,28141,NaN
7,Bhaag Milkha Bhaag,2013,186,8.2,NaN,65256,1.63
8,Hindi Medium,2017,132,7.9,NaN,26484,NaN
9,Sherlock Jr.,1924,45,8.2,NaN,46622,0.98
10,Bajrangi Bhaijaan,2015,163,8.0,NaN,81711,8.18
11,Drishyam,2013,160,8.3,NaN,38603,NaN
12,The Magdalene Sisters,2002,114,7.7,83.0,26801,4.89
13,Special 26,2013,144,8.0,NaN,54220,1.08
14,Vampire Hunter D: Bloodlust,2000,103,7.7,62.0,30813,0.15
15,Central Station,1998,110,8.0,80.0,38464,5.60
16,Barfi!,2012,151,8.1,NaN,79294,2.80
17,Nine Queens,2000,114,7.9,80.0,51630,1.22
18,Le Dîner de Cons,1998,80,7.7,73.0,40311,4.07
19,Kind Hearts and Coronets,1949,106,8.0,NaN,36327,NaN
20,Chak De! India,2007,153,8.2,68.0,77857,1.11
21,Love and Death,1975,85,7.7,89.0,37653,NaN
22,A Wednesday,2008,104,8.1,NaN,76771,NaN
23,Zelig,1983,79,7.7,NaN,41318,11.80
24,La Grande Illusion,1937,113,8.1,NaN,35546,0.17
25,Raazi,2018,138,7.8,NaN,28442,NaN
26,Sanjuro,1962,96,8.1,NaN,36925,NaN
27,Tae Guk Gi: The Brotherhood of War,2004,140,8.0,64.0,39014,1.11
28,C.R.A.Z.Y.,2005,129,7.9,81.0,32130,NaN
29,Udta Punjab,2016,148,7.8,NaN,29092,NaN
30,Andaz Apna Apna,1994,160,8.1,NaN,51951,NaN
31,The Circus,1928,72,8.1,90.0,32526,NaN
32,A Night at the Opera,1935,96,7.9,NaN,32007,2.54
33,Paan Singh Tomar,2012,135,8.2,NaN,35164,0.04
34,Vicky Donor,2012,126,7.8,NaN,41835,0.17
35,English Vinglish,2012,134,7.8,NaN,35249,1.67
36,Knockin' on Heaven's Door,1997,87,7.9,NaN,29200,0.00
37,OMG: Oh My God!,2012,125,8.1,NaN,55745,0.92
38,Dev.D,2009,144,8.0,NaN,29975,0.01
39,Sholay,1975,162,8.2,NaN,54026,NaN
40,Airlift,2016,130,8.0,NaN,55473,NaN
41,The Edge of Heaven,2007,122,7.8,85.0,31650,0.74
42,Hera Pheri,2000,156,8.2,NaN,62890,NaN
43,Kai Po Che,2013,120,7.8,40.0,35619,1.12
44,Munna Bhai M.B.B.S.,2003,156,8.1,NaN,78501,NaN
45,Vizontele,2001,110,8.0,NaN,35469,NaN
46,"Carry On, Munna Bhai",2006,144,8.1,NaN,45549,2.22
47,Udaan,2010,134,8.2,NaN,44146,0.01
48,The Breath,2009,128,8.0,NaN,32985,NaN
49,Anand,1971,122,8.2,NaN,33015,NaN